bienestar/bienestar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ayuda-integral/', include('ayuda_integral.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

handler404 = 'main.views.error.error_404_view'
handler500 = 'main.views.error.error_500_view'
handler403 = 'main.views.error.error_403_view'

bienestar/main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import pages,autentication
from ayuda_integral.views import expedientes
from main.views import profile

app_name='bienestar'

urlpatterns = [
    path('', pages.HomeView.as_view(), name='home'),
    path('redirecting/', pages.dispatch_view, name='dispatch'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', autentication.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', profile.profile_detail_view, name='profile'),
    path('expediente/reporte/', expedientes.ExpedienteReportView.as_view(), name='expediente-report'),
    path('expediente/reporte/<str:pk>/',expedientes.ExpedienteReporteVistaView.as_view(), name='vista-report'),
    path('expediente/reporte/actividad/<str:pk>/',expedientes.ExpedienteReporteActividadVistaView.as_view(), name='vista-report-actividad')
]

bienestar/main/models.py
"""
Modelos usados para el sistema de trámite documentario.

El diagrama de la base de datos se puede encontrar en el 
siguiente link: https://app.lucidchart.com/invitations/accept/b1ad9ddb-c7b3-4bc1-9b22-cb5aa67b99cf
"""

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin
from django.urls import reverse
from gdstorage.storage import GoogleDriveStorage

from furl import furl
import time

gd_storage = GoogleDriveStorage()

#metodos para obtener la ruta a la cual se subira los archivos, seran asi: CARPETA/apellidos, nombres (email)/archivo
CARPETA_COMPARTIDA = 'Archivos-Software Trámite Documentario/Convocatoria Comedor Universitario' #este es el nombre de la carpeta que se comparte con la cuenta de servicio del proyecto (https://developers.google.com/identity/protocols/oauth2/service-account)
def obtener_path_documento_expediente(instance, filename):
    return f'{CARPETA_COMPARTIDA}/{instance.expediente.usuario_beneficiario.apellidos}, {instance.expediente.usuario_beneficiario.nombres} ({instance.expediente.usuario_beneficiario.email})/{time.time()}{filename}'

def obtener_path_documento(instance, filename):
    return f'{CARPETA_COMPARTIDA}/{instance.usuario.apellidos}, {instance.usuario.nombres} ({instance.usuario.email})/{time.time()}{filename}'


class Area(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre


class Entidad(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(null=True, blank=True)
    I = 'I'
    S = 'S'
    B = 'B'
    N = 'N'
    C = 'C'
    AREAS_POSIBLES = [
        (I, "Ingenieria"),
        (S, "Sociales"),
        (B, "Biomedicas"),
        (N, "Independiente"),
        (C, "Central")
    ]
    area = models.CharField(max_length=1, choices=AREAS_POSIBLES, default=N)

    def __str__(self):
        return self.nombre


class Beneficiario(models.Model):
    nombres = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=30, null=True, blank=True)
    identificador = models.CharField(max_length=8, null=True, blank=True)
    is_interno = models.BooleanField(null=True, blank=True)

    DP = 'DE'
    SC = 'ES'
    SE = 'SE'
    ENTIDAD_POSIBLES = [
        (DP, "Dependencia"),
        (SC, "Escuela"),
        (SE, "Sector")
    ]
    tipo_entidad = models.CharField(
        max_length=2, choices=ENTIDAD_POSIBLES, default=SE)

    AL = 'AL'
    PR = 'PR'
    AD = 'AD'
    EX = 'EX'
    TIPOS_POSIBLES = [
        (AL, "Alumno"),
        (PR, "Profesor"),
        (AD, "Administrativo"),
        (EX, "Externo")
    ]
    tipo_rol = models.CharField(
        max_length=2, choices=TIPOS_POSIBLES, default=EX)
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)

    def __str__(self):
        return "{} {}".format(self.nombres, self.apellidos)


class Actividad(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre


class SubActividad(models.Model):
    nombre = models.CharField(max_length=250, null=True, blank=True)
    actividad = models.ForeignKey(
        Actividad, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "{} - {}".format(self.nombre, self.actividad)


class UserManager(BaseUserManager):

    def create_user(self, email, password, *args, **kwargs):
        model = self.model(
            email=self.normalize_email(email),
            rol=kwargs['rol'],
            oficina=kwargs['oficina']
        )
        model.set_password(password)
        model.save(using=self._db)
        return model

    def create_superuser(self, email, password, *args, **kwargs):
        model = self.model(
            email=self.normalize_email(email),
            rol=kwargs['rol'],
            oficina=kwargs['oficina']
        )
        model.is_staff = True
        model.is_admin = True
        model.is_superuser = True
        model.set_password(password)
        model.save(using=self._db)
        return model


class User(AbstractUser):
    """
    El usuario de la Subdirección de Bienestar Universitario
    o el solicitante.
    """
    nombres = models.CharField(max_length=60, blank=True)
    apellidos = models.CharField(max_length=60, blank=True)
    username = models.CharField(max_length=60, blank=True)
    email = models.EmailField(unique=True)
    
    google_profile_picture = models.URLField(max_length=200, default='', blank=True, null=True)

    AS = 'AS'
    SO = 'SO'
    SG = 'SG'
    SB = 'SB'
    JO = 'JO'
    TS = 'TS'
    BE = 'BE'
    ROLES_POSIBLES = [
        (AS, "Administrador general del sistema"),
        (SO, "Secretaria de oficina"),
        (SG, "Secretaria general"),
        (SB, "Jefe Sub-Dirección Bienestar"),
        (JO, "Jefe Oficina"),
        (TS, "Trabajador social"),
        (BE, "Solicitantes")
    ]
    rol = models.CharField(max_length=2, choices=ROLES_POSIBLES, default=TS)
    CU = 'CU'
    AI = 'AI'
    CJ = 'CJ'
    TR = 'TR'
    DM = 'DM'
    OFICINAS_POSIBLES = [
        #(CU, "Comedor Universitario"), #las otras oficinas estan ocultas porque aun no se han implementado
        (AI, "Ayuda Integral"),
        #(CJ, "Cuna Jardin"),
        #(TR, "Transporte"),
        #(DM, "Departamento Medico")
    ]
    oficina = models.CharField(
        max_length=2, choices=OFICINAS_POSIBLES, default=AI)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['rol', 'oficina']

    beneficiario = models.OneToOneField(
        Beneficiario, on_delete=models.CASCADE, null=True, blank=True)
    objects = UserManager()
    def __str__(self):
        return self.nombres


class Expediente(models.Model):
    fecha_recepcion = models.DateField()
    numero_expediente = models.CharField(max_length=30, unique=True)
    descripcion = models.TextField(null=True, blank=True)
    numero_proveido = models.CharField(max_length=30, blank=True)
    numero_oficio = models.CharField(max_length=30, blank=True)
    fecha_salida = models.DateField(null=True, blank=True)

    #dato para llenar el numero de expediente de entrada por solicitud
    n_expediente_solicitud = models.IntegerField(unique=True, null=True)

    #datos para llenar los correlativos de las salidas
    n_oficio = models.IntegerField(unique=True, null=True)
    n_proveido = models.IntegerField(unique=True, null=True)
    n_expediente = models.IntegerField(unique=True, null=True)
    n_informe = models.IntegerField(unique=True, null=True)

    #correlativos de salida
    salida_oficio = models.CharField(max_length=50, blank=True, null=True)
    salida_proveido = models.CharField(max_length=50, blank=True, null=True)
    salida_expediente = models.CharField(max_length=50, blank=True, null=True)
    salida_informe = models.CharField(max_length=50, blank=True, null=True)


    PE = 'PE'
    PR = 'PR'
    RE = 'RE'
    CO = 'CO'
    ESTADOS_POSIBLES = [(PE, "Pendiente"), (PR, "Proceso"),
                        (RE, "Revision"), (CO, "CONCLUIDO")]
    estado_expediente = models.CharField(
        max_length=2, choices=ESTADOS_POSIBLES, default=PE)
    usuario_beneficiario = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True,blank = True)
    beneficiario = models.ForeignKey(
        Beneficiario, on_delete=models.CASCADE, null=True,blank = True)
    actividad = models.ForeignKey(
        Actividad, on_delete=models.CASCADE, null=True)
    sub_actividad = models.ForeignKey(
        SubActividad, on_delete=models.CASCADE, null=True, blank=True)
    objects = models.Manager()
    PR = 'PR'
    PC = 'PC'
    IM = 'IM'
    RESULTADOS_POSIBLES = [(PR, "Proceso"), (PC, "Procedente"),
                        (IM, "Improcedente")]
    resultado = models.CharField(
        max_length=2, choices=RESULTADOS_POSIBLES, default=PR)
    def __str__(self):
        return "{} - {}".format(self.numero_expediente, self.beneficiario)


class Solicitud(models.Model):
    motivo = models.TextField()
    # beneficiario = models.OneToOneField(Beneficiario, on_delete=models.CASCADE, null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    AP = 'AP'
    DE = 'DE'
    PR = 'PR'
    problema = models.CharField(max_length=60)
    ESTADOS_POSIBLES = [(AP, "procedente "),
                        (DE, "improcedente"), (PR, "proceso")]
    estado_solicitud = models.CharField(
        max_length=2, choices=ESTADOS_POSIBLES, default=PR)
    expediente = models.OneToOneField(
        Expediente, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return "{} - {}".format(self.problema, self.usuario)
    
    @property
    def get_derivacion_trabajador_social(self):
        return UsuarioDerivacion.objects.get(usuario_derivado__rol=User.TS, expediente=self.expediente)


class UsuarioDerivacion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    usuario_derivado = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='usuario_derivado', null=True)
    expediente = models.ForeignKey(
        Expediente, on_delete=models.CASCADE, related_name='derivados')
    fecha = models.DateTimeField(auto_now_add=True)
    observacion = models.TextField(null=True, blank=True)

    def __str__(self):
        return "{} - {} - {}".format(self.usuario, self.expediente, self.usuario_derivado)


class HistorialDeExpediente(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    expediente = models.ForeignKey(
        Expediente, on_delete=models.CASCADE, related_name='historialDeCambios')
    fecha = models.DateTimeField(auto_now_add=True)
    titulo = models.TextField(null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return "{}".format(self.descripcion)


class TipoDocumento(models.Model):
    nombre = models.CharField(max_length=60)

bienestar/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",
                "value"       : "test",
                "class"       : "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",
                "value"       : "ApS12_ZZs8",                
                "class"       : "form-control"
            }
        ))

bienestar/main/views/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Usuario",
                "value"       : "",
                "class"       : "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Contraseña",
                "value"       : "",                
                "class"       : "form-control"
            }
        ))
    
class UploadDocumentForm(forms.Form):
    file = forms.FileField()
    image = forms.ImageField()

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

bienestar/main/views/autentication.py
# -*- encoding: utf-8 -*-


from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.forms.utils import ErrorList
from django.http import HttpResponse
from .forms import LoginForm
from django.urls import reverse

def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("bienestar:dispatch")
            else:    
                msg = 'Usuario o contraseña incorrectos'    
        else:
            msg = 'Hubo un error en la validación de los datos'    

    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect("bienestar:dispatch")

    return render(request, "accounts/login.html", {"form": form, "msg" : msg})

bienestar/main/views/error.py
from django.shortcuts import render

# Create your views here.


from django.http import HttpResponse

def error_404_view(request, exception):
    return render(request,'error-404.html')

def error_500_view(request):
    return render(request,'error-500.html')

def error_403_view(request, exception):
    return render(request,'error-403.html')

bienestar/main/views/pages.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from main.models import User

class HomeView(TemplateView):
    template_name='main/home.html'

@login_required()
def dispatch_view(request):
    user = request.user
    if user.rol == User.BE:
        return redirect(reverse('ayuda_integral:solicitud-list'))
    else:
        return redirect(reverse('ayuda_integral:expediente-list'))

bienestar/main/views/profile.py
from django.contrib.auth.decorators import login_required
from main.mixins import rol_permission_required
from django.shortcuts import render


@login_required()
@rol_permission_required(('AS', 'JO', 'TS', 'SG', 'SB', 'SO','BE'))
def profile_detail_view(request):
    '''Vista que muestra la información del usuario actual'''
    
    return render(
        request,
        template_name='main/profile.html',
        context={'user': request.user}
    )

bienestar/main/views/update.py
from django.shortcuts import render
from .forms import UploadDocumentForm, UploadFileForm
from django.http import HttpResponseRedirect
from main.mixins import RolPermisosMixin,rol_permission_required
from django.contrib.auth.decorators import login_required
# Imaginary function to handle an uploaded file.
# from somewhere import handle_uploaded_file

@login_required()
@rol_permission_required(('AS','JO','TS','SG','SB'))
def upload_doc(request):
    form = UploadDocumentForm()
    if request.method == 'POST':
        form = UploadDocumentForm(request.POST, request.FILES)  # Do not forget to add: request.FILES
        if form.is_valid():
            # Do something with our files or simply save them
            # if saved, our files would be located in media/ folder under the project's base folder
            model=form 
            form.save()
            print("hola")
    return render(request, 'main/update.html', locals())


@login_required()
@rol_permission_required(('AS','JO','TS','SG','SB'))
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form': form})

def handle_uploaded_file(f):
    with open('some/file/name.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

bienestar/main/templates/includes/footer-fullscreen.html
    <footer class="py-5">
      <div class="container">
        <div class="row align-items-center justify-content-xl-between">
          {% comment %} <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a target="_blank" 
                 href="https://www.unsa.edu.pe/" 
                 class="font-weight-bold ml-1">Universidad Nacional de San Agustin</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a class="font-weight-bold ml-1" target="_blank"> &copy; Dora la exploradora</a> 
                 - coded by <a target="_blank" href="http://fips.unsa.edu.pe/ingenieriadesistemas/">Escuela Profesional de Ingenieria de Sistemas</a>.
            </div>
          </div> {% endcomment %}
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                <a class="font-weight-bold ml-1" target="_blank">Universidad Nacional de San Agustín de Arequipa</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
               
            </div>
          </div>
        </div>
      </div>
    </footer>

bienestar/main/templates/includes/footer.html
      <!-- Footer -->
      <footer class="footer bg-transparent">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a target="_blank" 
                 href="https://www.unsa.edu.pe/" 
                 class="font-weight-bold ml-1">Universidad Nacional de San Agustín de Arequipa</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a class="font-weight-bold ml-1" target="_blank"> &copy; copyright</a> 
                 - coded by <a target="_blank" href="http://fips.unsa.edu.pe/ingenieriadesistemas/">Escuela Profesional de Ingeniería de Sistemas</a>
            </div>
          </div>
        </div>
      </footer>

bienestar/main/templates/includes/navigation-fullscreen.html
    <!-- Navbar -->
    <nav class="navbar navbar-top navbar-horizontal navbar-expand-md navbar-dark" style="position: absolute;">
      <div class="container px-10">
        <a class="navbar-brand" href="/">
          <img src="/static/assets/img/unsa/unsa-negativo.png" alt="..."/>
        </a>
      </div>
    </nav>

bienestar/main/templates/includes/navigation.html
<!-- Navbar -->
<nav class="navbar navbar-top navbar-expand-md navbar-dark bg-primary" id="navbar-main">
  <div class="container-fluid">
    <!-- Brand -->
    <label class="d-lg-inline-block"></label>
    <!-- Form -->
    {% comment %} <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
      <div class="form-group mb-0">
        <div class="input-group input-group-alternative">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-search"></i></span>
          </div>
          <input class="form-control" placeholder="Search" type="text">
        </div>
      </div>
    </form> {% endcomment %}

    <ul class="navbar-nav align-items-center d-none d-md-flex ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <div class="media align-items-center">
            <span class="avatar avatar-sm rounded-circle bg-white">
              <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-bell" fill="#500"
                xmlns="http://www.w3.org/2000/svg">
                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2z" />
                <path fill-rule="evenodd"
                  d="M8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z" />
              </svg>
            </span>
            <div class="media-body ml-2 d-none d-lg-block">
              <span class="mb-0 text-sm  font-weight-bold">
                {{request.user.notifications.unread|length}} Notificaciones
              </span>
            </div>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-center pb-0 overflow-hidden mb-4"
          style="width: 320px;">
          <div class=" dropdown-header noti-title">
            <h6 class="text-overflow m-0">Notificaciones</h6>
          </div>






          {% for notificacion in request.user.notifications.all %}
          <hr class="my-0 p-0">
          <a href="{% url 'ayuda_integral:redireccionar-de-notificacion' notificacion.pk%}">
            <div class="dropdown-item m-0  item-notificacion">
              <div class="row">
                <div class="col-11">
                  <h5 class="mb-0">{{notificacion.verb|capfirst}}</h5>

                </div>
                <div class="col-1 p-0">
                  {% if notificacion.unread %}
                  <div class="notificacion-punto ml-2 mt-1"></div>
                  {% endif %}
                </div>
              </div>
              <small>{{notificacion.description|default:""|capfirst}}</small>
              <small><strong class="text-primary">{{notificacion.action_object.nombre|default:""|capfirst}}</strong></small>
              <label class="text-muted d-block"><small>{{notificacion.timestamp|date:'d M. h:i:s a'}}</small></label>

            </div>
          </a>


          {% endfor %}

        </div>
      </li>
    </ul>



    <!-- User -->
    <ul class="navbar-nav align-items-center d-none d-md-flex">
      <li class="nav-item dropdown">
        <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <div class="media align-items-center">
            <span class="avatar avatar-sm rounded-circle bg-white">
              {% if request.user.google_profile_picture == "" %}
                <img alt="Image placeholder" src="/static/assets/img/theme/team-5-800x800.jpg">
              {% else %}
                <img alt="Perfil" src="{{ request.user.google_profile_picture }}">
              {% endif %}
            </span>
            <div class="media-body ml-2 d-none d-lg-block">
              <span class="mb-0 text-sm  font-weight-bold">
                {{ request.user.email }}
              </span>
            </div>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
          <div class=" dropdown-header noti-title">
            <h6 class="text-overflow m-0">Bienvenido</h6>
          </div>
          <a href="{% url 'bienestar:profile' %}" class="dropdown-item">
            <i class="ni ni-single-02"></i>
            <span>Ver Perfil</span>
          </a>
          <a href="{% url 'bienestar:logout' %}" class="dropdown-item">
            <i class="ni ni-user-run"></i>
            <span>Salir</span>
          </a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!-- End Navbar -->

bienestar/main/templates/includes/scripts-fullscreen.html
  <!--   Core   -->
  <script src="/static/assets/js/plugins/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <!--   Optional JS   -->
  <!--   Argon JS   -->
  <script src="/static/assets/js/argon-dashboard.min.js?v=1.1.0"></script>

bienestar/main/templates/includes/scripts.html
  <!--   Core   -->
  <script src="/static/assets/js/plugins/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <!--   Optional JS   -->
  <script src="/static/assets/js/plugins/chart.js/dist/Chart.min.js"></script>
  <script src="/static/assets/js/plugins/chart.js/dist/Chart.extension.js"></script>

  <!--   Argon JS   -->
  <script src = '/static/assets/js/argon-dashboard.min.js?v=1.1.0'></script>

  <!--Selectize-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.js" integrity="sha512-WZ3VAWLJDOQRwRtR4nkn7g7Fb+TSDtdpdQdJgM5tSn82RKD/O84EqMPKqvF+3ypk5+IErlevC4WpbdbRG65uIg==" crossorigin="anonymous"></script>

  <script src='/static/assets/js/plugins/jquery/dist/jquery.chained.min.js'> </script>