bienestar/ayuda_integral/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from ayuda_integral.url_patterns import expedientes, notificaciones
from django.contrib.auth.decorators import login_required, permission_required
from ayuda_integral.url_patterns import beneficiarios, solicitudes, derivacion, apoyoPsico, entidad


app_name = 'ayuda_integral'

urlpatterns = [
    path('',TemplateView.as_view(template_name='ayuda_integral/home.html'), name='home'),
    path('expedientes/', include(expedientes.urlpatterns)),
    path('expedientes/', include(derivacion.urlpatterns)),
    path('beneficiario/',include(beneficiarios.urlpatterns)),
    path('solicitud/',include(solicitudes.urlpatterns)),
    path('apoyoPsico/',include(apoyoPsico.urlpatterns)), 
    path('notificaciones/', include(notificaciones.urlpatterns)),
    path('entidad/', include(entidad.urlpatterns))
]

bienestar/bienestar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ayuda-integral/', include('ayuda_integral.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

handler404 = 'main.views.error.error_404_view'
handler500 = 'main.views.error.error_500_view'
handler403 = 'main.views.error.error_403_view'

bienestar/main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import pages,autentication
from ayuda_integral.views import expedientes
from main.views import profile

app_name='bienestar'

urlpatterns = [
    path('', pages.HomeView.as_view(), name='home'),
    path('redirecting/', pages.dispatch_view, name='dispatch'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', autentication.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', profile.profile_detail_view, name='profile'),
    path('expediente/reporte/', expedientes.ExpedienteReportView.as_view(), name='expediente-report'),
    path('expediente/reporte/<str:pk>/',expedientes.ExpedienteReporteVistaView.as_view(), name='vista-report'),
    path('expediente/reporte/actividad/<str:pk>/',expedientes.ExpedienteReporteActividadVistaView.as_view(), name='vista-report-actividad')
]

bienestar/main/models.py
"""
Modelos usados para el sistema de trámite documentario.

El diagrama de la base de datos se puede encontrar en el 
siguiente link: https://app.lucidchart.com/invitations/accept/b1ad9ddb-c7b3-4bc1-9b22-cb5aa67b99cf
"""

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin
from django.urls import reverse
from gdstorage.storage import GoogleDriveStorage

from furl import furl
import time

gd_storage = GoogleDriveStorage()

#metodos para obtener la ruta a la cual se subira los archivos, seran asi: CARPETA/apellidos, nombres (email)/archivo
CARPETA_COMPARTIDA = 'Archivos-Software Trámite Documentario/Convocatoria Comedor Universitario' #este es el nombre de la carpeta que se comparte con la cuenta de servicio del proyecto (https://developers.google.com/identity/protocols/oauth2/service-account)
def obtener_path_documento_expediente(instance, filename):
    return f'{CARPETA_COMPARTIDA}/{instance.expediente.usuario_beneficiario.apellidos}, {instance.expediente.usuario_beneficiario.nombres} ({instance.expediente.usuario_beneficiario.email})/{time.time()}{filename}'

def obtener_path_documento(instance, filename):
    return f'{CARPETA_COMPARTIDA}/{instance.usuario.apellidos}, {instance.usuario.nombres} ({instance.usuario.email})/{time.time()}{filename}'


class Area(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre


class Entidad(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(null=True, blank=True)
    I = 'I'
    S = 'S'
    B = 'B'
    N = 'N'
    C = 'C'
    AREAS_POSIBLES = [
        (I, "Ingenieria"),
        (S, "Sociales"),
        (B, "Biomedicas"),
        (N, "Independiente"),
        (C, "Central")
    ]
    area = models.CharField(max_length=1, choices=AREAS_POSIBLES, default=N)

    def __str__(self):
        return self.nombre


class Beneficiario(models.Model):
    nombres = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=30, null=True, blank=True)
    identificador = models.CharField(max_length=8, null=True, blank=True)
    is_interno = models.BooleanField(null=True, blank=True)

    DP = 'DE'
    SC = 'ES'
    SE = 'SE'
    ENTIDAD_POSIBLES = [
        (DP, "Dependencia"),
        (SC, "Escuela"),
        (SE, "Sector")
    ]
    tipo_entidad = models.CharField(
        max_length=2, choices=ENTIDAD_POSIBLES, default=SE)

    AL = 'AL'
    PR = 'PR'
    AD = 'AD'
    EX = 'EX'
    TIPOS_POSIBLES = [
        (AL, "Alumno"),
        (PR, "Profesor"),
        (AD, "Administrativo"),
        (EX, "Externo")
    ]
    tipo_rol = models.CharField(
        max_length=2, choices=TIPOS_POSIBLES, default=EX)
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)

    def __str__(self):
        return "{} {}".format(self.nombres, self.apellidos)


class Actividad(models.Model):
    nombre = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre


class SubActividad(models.Model):
    nombre = models.CharField(max_length=250, null=True, blank=True)
    actividad = models.ForeignKey(
        Actividad, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "{} - {}".format(self.nombre, self.actividad)


class UserManager(BaseUserManager):

    def create_user(self, email, password, *args, **kwargs):
        model = self.model(
            email=self.normalize_email(email),
            rol=kwargs['rol'],
            oficina=kwargs['oficina']
        )
        model.set_password(password)
        model.save(using=self._db)
        return model

    def create_superuser(self, email, password, *args, **kwargs):
        model = self.model(
            email=self.normalize_email(email),
            rol=kwargs['rol'],
            oficina=kwargs['oficina']
        )
        model.is_staff = True
        model.is_admin = True
        model.is_superuser = True
        model.set_password(password)
        model.save(using=self._db)
        return model


class User(AbstractUser):
    """
    El usuario de la Subdirección de Bienestar Universitario
    o el solicitante.
    """
    nombres = models.CharField(max_length=60, blank=True)
    apellidos = models.CharField(max_length=60, blank=True)
    username = models.CharField(max_length=60, blank=True)
    email = models.EmailField(unique=True)
    
    google_profile_picture = models.URLField(max_length=200, default='', blank=True, null=True)

    AS = 'AS'
    SO = 'SO'
    SG = 'SG'
    SB = 'SB'
    JO = 'JO'
    TS = 'TS'
    BE = 'BE'
    ROLES_POSIBLES = [
        (AS, "Administrador general del sistema"),
        (SO, "Secretaria de oficina"),
        (SG, "Secretaria general"),
        (SB, "Jefe Sub-Dirección Bienestar"),
        (JO, "Jefe Oficina"),
        (TS, "Trabajador social"),
        (BE, "Solicitantes")
    ]
    rol = models.CharField(max_length=2, choices=ROLES_POSIBLES, default=TS)
    CU = 'CU'
    AI = 'AI'
    CJ = 'CJ'
    TR = 'TR'
    DM = 'DM'
    OFICINAS_POSIBLES = [
        #(CU, "Comedor Universitario"), #las otras oficinas estan ocultas porque aun no se han implementado
        (AI, "Ayuda Integral"),
        #(CJ, "Cuna Jardin"),
        #(TR, "Transporte"),
        #(DM, "Departamento Medico")
    ]
    oficina = models.CharField(
        max_length=2, choices=OFICINAS_POSIBLES, default=AI)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['rol', 'oficina']

    beneficiario = models.OneToOneField(
        Beneficiario, on_delete=models.CASCADE, null=True, blank=True)
    objects = UserManager()
    def __str__(self):
        return self.nombres


class Expediente(models.Model):
    fecha_recepcion = models.DateField()
    numero_expediente = models.CharField(max_length=30, unique=True)
    descripcion = models.TextField(null=True, blank=True)
    numero_proveido = models.CharField(max_length=30, blank=True)
    numero_oficio = models.CharField(max_length=30, blank=True)
    fecha_salida = models.DateField(null=True, blank=True)

    #dato para llenar el numero de expediente de entrada por solicitud
    n_expediente_solicitud = models.IntegerField(unique=True, null=True)

    #datos para llenar los correlativos de las salidas
    n_oficio = models.IntegerField(unique=True, null=True)
    n_proveido = models.IntegerField(unique=True, null=True)
    n_expediente = models.IntegerField(unique=True, null=True)
    n_informe = models.IntegerField(unique=True, null=True)

    #correlativos de salida
    salida_oficio = models.CharField(max_length=50, blank=True, null=True)
    salida_proveido = models.CharField(max_length=50, blank=True, null=True)
    salida_expediente = models.CharField(max_length=50, blank=True, null=True)
    salida_informe = models.CharField(max_length=50, blank=True, null=True)


    PE = 'PE'
    PR = 'PR'
    RE = 'RE'
    CO = 'CO'
    ESTADOS_POSIBLES = [(PE, "Pendiente"), (PR, "Proceso"),
                        (RE, "Revision"), (CO, "CONCLUIDO")]
    estado_expediente = models.CharField(
        max_length=2, choices=ESTADOS_POSIBLES, default=PE)
    usuario_beneficiario = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True,blank = True)
    beneficiario = models.ForeignKey(
        Beneficiario, on_delete=models.CASCADE, null=True,blank = True)
    actividad = models.ForeignKey(
        Actividad, on_delete=models.CASCADE, null=True)
    sub_actividad = models.ForeignKey(
        SubActividad, on_delete=models.CASCADE, null=True, blank=True)
    objects = models.Manager()
    PR = 'PR'
    PC = 'PC'
    IM = 'IM'
    RESULTADOS_POSIBLES = [(PR, "Proceso"), (PC, "Procedente"),
                        (IM, "Improcedente")]
    resultado = models.CharField(
        max_length=2, choices=RESULTADOS_POSIBLES, default=PR)
    def __str__(self):
        return "{} - {}".format(self.numero_expediente, self.beneficiario)


class Solicitud(models.Model):
    motivo = models.TextField()
    # beneficiario = models.OneToOneField(Beneficiario, on_delete=models.CASCADE, null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    AP = 'AP'
    DE = 'DE'
    PR = 'PR'
    problema = models.CharField(max_length=60)
    ESTADOS_POSIBLES = [(AP, "procedente "),
                        (DE, "improcedente"), (PR, "proceso")]
    estado_solicitud = models.CharField(
        max_length=2, choices=ESTADOS_POSIBLES, default=PR)
    expediente = models.OneToOneField(
        Expediente, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return "{} - {}".format(self.problema, self.usuario)
    
    @property
    def get_derivacion_trabajador_social(self):
        return UsuarioDerivacion.objects.get(usuario_derivado__rol=User.TS, expediente=self.expediente)


class UsuarioDerivacion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    usuario_derivado = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='usuario_derivado', null=True)
    expediente = models.ForeignKey(
        Expediente, on_delete=models.CASCADE, related_name='derivados')
    fecha = models.DateTimeField(auto_now_add=True)
    observacion = models.TextField(null=True, blank=True)

    def __str__(self):
        return "{} - {} - {}".format(self.usuario, self.expediente, self.usuario_derivado)


class HistorialDeExpediente(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    expediente = models.ForeignKey(
        Expediente, on_delete=models.CASCADE, related_name='historialDeCambios')
    fecha = models.DateTimeField(auto_now_add=True)
    titulo = models.TextField(null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return "{}".format(self.descripcion)


class TipoDocumento(models.Model):
    nombre = models.CharField(max_length=60)

bienestar/ayuda_integral/views/apoyoPsico.py
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.generic import *
from main import api
from django import forms
from django.shortcuts import render
from main.mixins import RolPermisosMixin,rol_permission_required

@login_required()
@rol_permission_required(('AS','SG','SO','SB','JO','TS'))
def apoyoListView(request):
    solicitudes = api.apoyoPsicopedagogico()
    return render(request,template_name='ayuda_integral/apoyoPsico/list.html',context={'solicitudes':solicitudes})
    
@login_required()
@rol_permission_required(('AS','SG','SO','SB','JO','TS'))
def buscarSolicitudApoyoView(request):
    campo = request.POST.get('campo','')
    tipo = request.POST.get('tipo', '')
    solicitudes = {}
    if len(campo) != 0 and tipo == "DNI":
        solicitudes = api.obtenerSolicitudApoyoDNI(campo)
    elif len(campo) != 0 and tipo == 'CUI':
        solicitudes = api.obtenerSolicitudApoyoCUI(campo)
    else:
        print("no ingreso nada") 
    return render(request,template_name='ayuda_integral/apoyoPsico/list.html',context={'solicitudes':solicitudes})

bienestar/ayuda_integral/views/derivacion.py
from main.models import UsuarioDerivacion, User, Expediente
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from main.mixins import RolPermisosMixin,rol_permission_required
from notifications.signals import notify

from django.db.models import Max

class Derivacion():
    def __init__(self,
     expediente = None, emisor = None, receptor = None):
        self.expediente = expediente
        self.emisor = emisor
        self.receptor = receptor

def derivar(derivacion: Derivacion):
    # Crear un nuevo objeto usuario derivacion con los datos de derivacion
    UsuarioDerivacion.objects.create(
        usuario= derivacion.emisor,
        usuario_derivado= derivacion.receptor,
        expediente= derivacion.expediente,
    )

    #crear una notificacion para el receptor de la derivacion
    notify.send(
        derivacion.emisor, 
        recipient=derivacion.receptor, 
        action_object=derivacion.expediente,
        verb='Te han derivado un expediente',
        description=f'{derivacion.emisor.email} te ha derivado el expediente:'
    )

def derivacion_oficina(emisor, oficina, expediente):
    '''
    Send the newly created expediente to the office's secretary
    '''
    usuario_destino = User.objects.get(
        oficina = oficina,
        rol = User.SO
    )

    
    derivar(Derivacion(
        emisor=emisor,
        receptor=usuario_destino,
        expediente=expediente
    ))

@login_required()
@rol_permission_required(('AS','SG','SO'))
def derivacion_trabajador_view(request):
    '''
    Send a list of expedientes to a list of workers
    '''
    user = request.user
    if request.method == "POST":
        # Se obtiene la lista de pks de expedientes y de usuarios
        expedientes = request.POST.get('expedientes', [])
        receptores = request.POST.get('usuarios', [])

        if isinstance(expedientes, str):
            expedientes = [expedientes]
            
        if isinstance(receptores, str):
            receptores = [receptores]
        

        for expediente_pk in expedientes:
            for receptor_pk in receptores:
                expediente = Expediente.objects.get(pk= expediente_pk)
                receptor = User.objects.get(pk= receptor_pk)
                
                derivar(Derivacion(
                    emisor=user,
                    expediente=expediente,
                    receptor=receptor
                ))
                
                messages.success(
                    request,
                    f'Se derivó el expediente {expediente} al usuario {receptor} satisfactoriamente',
                )
                #asignar un numero de informe a cada expediente que se esta derivando
                max_inf = Expediente.objects.all().aggregate(Max('n_informe'))['n_informe__max']
                expediente.n_informe = max_inf + 1 if max_inf is not None else 1
                expediente.salida_informe = f'{expediente.n_informe:04d}-2021/OAIU-SDBU'
                
                expediente.save()
        
    return redirect(
        #reverse('ayuda_integral:expediente-list')
        #redireccionar a la misma pagina de donde derivamos
        request.META.get('HTTP_REFERER')
    )

bienestar/ayuda_integral/views/notificaciones.py
from django.shortcuts import redirect
from django.views.generic import DetailView
from main.models import User, Expediente



class NotificacionView(DetailView):
    def get(self, request, pk):
        notification = request.user.notifications.get(pk=pk)
        notification.unread = False
        notification.save()
        action_object = notification.action_object
        if isinstance(action_object, Expediente):
            return redirect("ayuda_integral:expediente-detail", pk=action_object.pk)
        
        return redirect("ayuda_integral:expediente-list")

bienestar/ayuda_integral/templates/ayuda_integral/expediente/create_form.html
{% extends 'layouts/base.html' %}
{% block content %}

<div class="container-fluid mt-4">

    <div class="row">
        <div class="col-xl-8 order-xl-1 order-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Crear expediente</h3>
                        </div>
                        <div class="col-4">
                            
                        </div>

                    </div>
                </div>
                <div class="card-body">

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label>Fecha de recepción</label>
                                <input type="date"
                                    class="form-control form-control-alternative {%if form.fecha_recepcion.errors %}is-invalid{%endif%}"
                                    placeholder="{{form.fecha_recepcion.label}}"
                                    id="fechaRecepcion"
                                    value="{{form.fecha_recepcion.value|default:''}}"
                                    name="{{form.fecha_recepcion.html_name}}">
                                    
                                <div class="invalid-feedback">
                                    {{form.fecha_recepcion.errors}}
                                </div>
                            </div>

                            <div class="form-group col-md-4">
                                <label>Número de expediente</label>
                                <input type="text" readonly
                                    class="form-control form-control-alternative {%if form.numero_expediente.errors %}is-invalid{%endif%}"
                                    placeholder="Número de expediente" id="{{form.numero_expediente.id_for_label}}"
                                    value="{{form.numero_expediente.value|default:'Se generará automáticamente'}}"
                                    name="{{form.numero_expediente.html_name}}">
                                <div class="invalid-feedback">
                                    {{form.numero_expediente.errors}}
                                </div>
                            </div>

                            <div class="form-group col-md-4">
                                <label>Número proveído</label>
                                <input type="text"
                                    class="form-control form-control-alternative {%if form.numero_proveido.errors %}is-invalid{%endif%}"
                                    placeholder="Número proveído" id="{{form.numero_proveido.id_for_label}}"
                                    value="{{form.numero_proveido.value|default:''}}"
                                    name="{{form.numero_proveido.html_name}}">
                                <div class="invalid-feedback">
                                    {{form.numero_proveido.errors}}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            {% if not pk%}
                            <div class="form-group col-md-8">
                                <label>{{form.beneficiario.label}}</label>
                                <select id="{{form.beneficiario.id_for_label}}" name="{{form.beneficiario.html_name}}" required
                                    class=" {%if form.beneficiario.errors %}is-invalid{%endif%} selectize-item">
                                    {% for item in beneficiario%}
                                    <option value="{{item.id}}">{{item}}</option>
                                    {% endfor %}
                                </select>
                                <input type="hidden" id="dummy" class="{%if form.beneficiario.errors %}is-invalid{%endif%} form-control">
                                <div class="invalid-feedback">
                                    {{form.beneficiario.errors}}
                                </div>
                            </div>
                            {% endif %}
                            <div class="form-group col-md-4">
                                <label>Oficina a derivar</label>
                                <select name="oficina_a_derivar" class="form-control form-control-alternative">
                                    {% for oficina in oficinas%}
                                    <option value="{{oficina.0}}">{{oficina.1}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label>Salida a crear</label>
                                <select name="salida_a_crear" id="salida_a_crear" class="form-control form-control-alternative">
                                    <option value="oficio">Número de Oficio</option>
                                    <option value="proveido">Número de Proveído</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label>Número oficio</label>
                                <input type="text"
                                    class="form-control form-control-alternative {%if form.numero_oficio.errors %}is-invalid{%endif%}"
                                    placeholder="Número oficio" id="{{form.numero_oficio.id_for_label}}"
                                    value="{{form.numero_oficio.value|default:''}}"
                                    name="{{form.numero_oficio.html_name}}">
                                <div class="invalid-feedback">
                                    {{form.numero_oficio.errors}}
                                </div>
                            </div>

                            

                            <div class="form-group col-md-4">
                                <label>{{form.actividad.label}}</label>
                                <select id="{{form.actividad.id_for_label}}" name="{{form.actividad.html_name}}"
                                    class="form-control form-control-alternative  {%if form.actividad.errors %}is-invalid{%endif%}">
                                    <option value ="0">---------</option>
                                    {% for item in actividad%}
                                    <option value={{item.id }} {% if item.id|slugify == form.actividad.value%} selected {% endif %}>{{item.nombre }} </option>
                                    {% endfor %}
                                </select>

                                <div class="invalid-feedback">
                                    {{form.actividad.errors}}
                                </div>
                            </div>
                            <div class="form-group col-md-4">
                                <label>{{form.sub_actividad.label}}</label>
                                <select id="{{form.sub_actividad.id_for_label}}" name="{{form.sub_actividad.html_name}}"
                                    class="form-control  {%if form.sub_actividad.errors %}is-invalid{%endif%}">
                                    <option data-chained="0">Primero escoge una actividad</option>
                                    {% for item in subactividad %}                                    
                                    <option value="{{item.id}}" data-chained="{{item.actividad.id}}" {% if item.id|slugify == form.sub_actividad.value|default:''%} selected {% endif %}>{{item.nombre }} </option>
                                    {% endfor %}
                                </select>

                                <div class="invalid-feedback">
                                    {{form.sub_actividad.errors}}
                                </div>
                            </div>

                        </div>

                        <div class="form-group">
                            <label>Descripción</label>
                            <textarea cols="30" rows="10" placeholder="Descripción"
                                id="{{form.descripcion.id_for_label}}" name="{{form.descripcion.html_name}}"
                                class="form-control form-control-alternative {%if form.descripcion.errors %}is-invalid{%endif%}">{{form.descripcion.value|default:''}}</textarea>
                            <div class="invalid-feedback">
                                {{form.descripcion.errors}}
                            </div>
                        </div>


                        <button type="reset" class="btn btn-danger float-left"
                            onclick="javascript:window.history.back();">
                            <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-x" fill="currentColor"
                                xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                            </svg>
                            Cancelar
                        </button>
                        <button type="submit" class="btn btn-success float-right">
                            <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-check" fill="currentColor"
                                xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                    d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z" />
                            </svg>
                            Guardar
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-xl-4 order-xl-2 order-2 mb-5 mb-xl-0">

            <div class="card card-profile shadow">

                <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
                    <h2>Crear expediente</h2>
                </div>
                <div class="card-body pt-0 pt-md-4">
                    <ul>
                        <li>FECHA DE RECEPCIÓN: Se debe colocar la fecha la recepción del expediente. No se pueden colocar fechas futuras</li>
                        <li>N° DE EXPEDIENTE: (Obligatorio)</li>
                        <li>PROVEÍDO: Número de proveído</li>
                        <li>NOMBRE BENEFICIARIO: Debe escoger al beneficiario creado en el módulo de benficiarios</li>
                        <li>OFICINA: Oficina a la que se deriva el expediente</li>
                        <li>N° DE OFICIO: Número de oficio</li>
                        <li>ACTIVIDAD: Escoger la actividad a la que pertenece el expediente.</li>
                        <li>SUBACTIVIDAD: Se debe escoger la subactividad de la actividad escogida.</li>
                        <li>DESCRIPCIÓN: Se debe colocar una breve descripción del expediente.</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

    {% include "includes/footer.html" %}

</div>

{% endblock %}

{% block stylesheets %}
<style type="text/css">
    .selectize-item .selectize-input{
        display: block;
        width: 100%;
        height: calc(2.75rem + 2px);
        padding: 0.625rem 0.75rem; 
        font-size: 1rem;
        line-height: 1.5;
        color: #6c757d;
        background-color: #fff !important;
        background-clip: padding-box;
        border: 1px solid #cad1d7;
        border-radius: 0.375rem;
        box-shadow: none;
        transition: all 0.2s cubic-bezier(0.68, -0.55, 0.265, 1.55);
        font-size: 11px;
    }
	
</style>
{% endblock %}

{% block javascripts %}
<script>
    $('.selectize-item').selectize({
        sortField: 'text',
        delimiter: ',',
        persist: false,
        maxItems: 1  
    });
    
    //solo se puede seleccionar las fechas hasta hoy
    var hoy = new Date();
    var dia = hoy.getDate();
    var mes = hoy.getMonth() + 1;
    var anio = hoy.getFullYear();

    $("#fechaRecepcion").attr("max", anio + '-' + (mes>9?mes:'0'+mes) + '-' + (dia>9?dia:'0'+dia));
    $("#fechaRecepcion").attr("value", anio + '-' + (mes>9?mes:'0'+mes) + '-' + (dia>9?dia:'0'+dia));


    $(function(){
        $("#id_sub_actividad").chained("#id_actividad")
    })
</script>
{% endblock %}

bienestar/ayuda_integral/templates/ayuda_integral/expediente/document.html
<a href="{% url 'ayuda_integral:expediente-doc-create' pk %}">Subir</a>

{% if object_list %}
    <h3> Documentos del expediente:</h3>
    {% for documento in object_list %}
        <p> <a href="{{documento.path.url}}">{{documento.nombre}}</a></p>
    {% endfor %}
{% endif %}
{% if docPersonal %}
    <h3> Documentos del beneficiario:</h3>
    {% for documento in docPersonal %}
        <p> <a href="{{documento.path.url}}">{{documento.tipo_documento}}</a></p>
    {% endfor %}
{% endif %}