bienestar/ayuda_integral/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from ayuda_integral.url_patterns import expedientes, notificaciones
from django.contrib.auth.decorators import login_required, permission_required
from ayuda_integral.url_patterns import beneficiarios, solicitudes, derivacion, apoyoPsico, entidad


app_name = 'ayuda_integral'

urlpatterns = [
    path('',TemplateView.as_view(template_name='ayuda_integral/home.html'), name='home'),
    path('expedientes/', include(expedientes.urlpatterns)),
    path('expedientes/', include(derivacion.urlpatterns)),
    path('beneficiario/',include(beneficiarios.urlpatterns)),
    path('solicitud/',include(solicitudes.urlpatterns)),
    path('apoyoPsico/',include(apoyoPsico.urlpatterns)), 
    path('notificaciones/', include(notificaciones.urlpatterns)),
    path('entidad/', include(entidad.urlpatterns))
]

bienestar/bienestar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ayuda-integral/', include('ayuda_integral.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

handler404 = 'main.views.error.error_404_view'
handler500 = 'main.views.error.error_500_view'
handler403 = 'main.views.error.error_403_view'

bienestar/main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import pages,autentication
from ayuda_integral.views import expedientes
from main.views import profile

app_name='bienestar'

urlpatterns = [
    path('', pages.HomeView.as_view(), name='home'),
    path('redirecting/', pages.dispatch_view, name='dispatch'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', autentication.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', profile.profile_detail_view, name='profile'),
    path('expediente/reporte/', expedientes.ExpedienteReportView.as_view(), name='expediente-report'),
    path('expediente/reporte/<str:pk>/',expedientes.ExpedienteReporteVistaView.as_view(), name='vista-report'),
    path('expediente/reporte/actividad/<str:pk>/',expedientes.ExpedienteReporteActividadVistaView.as_view(), name='vista-report-actividad')
]

bienestar/ayuda_integral/views/apoyoPsico.py
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.generic import *
from main import api
from django import forms
from django.shortcuts import render
from main.mixins import RolPermisosMixin,rol_permission_required

@login_required()
@rol_permission_required(('AS','SG','SO','SB','JO','TS'))
def apoyoListView(request):
    solicitudes = api.apoyoPsicopedagogico()
    return render(request,template_name='ayuda_integral/apoyoPsico/list.html',context={'solicitudes':solicitudes})
    
@login_required()
@rol_permission_required(('AS','SG','SO','SB','JO','TS'))
def buscarSolicitudApoyoView(request):
    campo = request.POST.get('campo','')
    tipo = request.POST.get('tipo', '')
    solicitudes = {}
    if len(campo) != 0 and tipo == "DNI":
        solicitudes = api.obtenerSolicitudApoyoDNI(campo)
    elif len(campo) != 0 and tipo == 'CUI':
        solicitudes = api.obtenerSolicitudApoyoCUI(campo)
    else:
        print("no ingreso nada") 
    return render(request,template_name='ayuda_integral/apoyoPsico/list.html',context={'solicitudes':solicitudes})

bienestar/ayuda_integral/views/beneficiarios.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.generic import *
from main import models
from main.models import Beneficiario, Entidad
from django import forms
from main.mixins import RolPermisosMixin,rol_permission_required
from django.db.models import Q
from django.contrib import messages

from ayuda_integral.forms import BeneficiarioForm, BeneficiarioUpdateForm

class SolicitantesExternosListView(LoginRequiredMixin,RolPermisosMixin, ListView):
    rol_permission_required = ('AS','SG','SO','SB','JO','TS')
    model = Beneficiario
    paginate_by = 10
    template_name = 'ayuda_integral/beneficiario/externo_list.html'

    def get_queryset(self):
        buscar = self.request.GET.get('buscar', '')
        return self.model.objects.filter(is_interno=False).filter(Q(nombres__icontains = buscar) | Q(apellidos__icontains = buscar) | Q(identificador__icontains = buscar))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['buscar'] = self.request.GET.get('buscar', '')
        return context


class SolicitantesInternosListView(LoginRequiredMixin,RolPermisosMixin, ListView):
    rol_permission_required = ('AS','SG','SO','SB','JO','TS')
    model = Beneficiario
    paginate_by = 10
    template_name = 'ayuda_integral/beneficiario/interno_list.html'

    def get_queryset(self):
        buscar = self.request.GET.get('buscar', '')
        return self.model.objects.filter(is_interno=True).filter(Q(nombres__icontains = buscar) | Q(apellidos__icontains = buscar) | Q(identificador__icontains = buscar))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['buscar'] = self.request.GET.get('buscar', '')
        return context


class BeneficiarioExternoDetailView(LoginRequiredMixin,RolPermisosMixin, DetailView):
    rol_permission_required = ('AS','SG','SO','SB','JO','TS')
    model = models.Beneficiario
    template_name = 'ayuda_integral/beneficiario/detail.html'

class BeneficiarioExternoCreateView(LoginRequiredMixin,RolPermisosMixin, CreateView):
    rol_permission_required = ('AS','SG')
    model = models.Beneficiario
    form_class = BeneficiarioForm
    
    template_name = 'ayuda_integral/beneficiario/create_form.html'
    
    def form_valid(self, form):
        benefExt = models.Beneficiario(
            is_interno = False,
            tipo_entidad = 'DE',
            tipo_rol = 'EX',
            nombres = form.cleaned_data['nombres'],
            apellidos = form.cleaned_data['apellidos'],
            identificador = form.cleaned_data['identificador'],
            entidad = form.cleaned_data['entidad']
        )
        benefExt.save()


    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['entidades'] = models.Entidad.objects.filter(Q(area=models.Entidad.C)|Q(area=models.Entidad.N))
        
        return context


    
    def get_success_url(self):
        return reverse('ayuda_integral:beneficiario-externo-detail', args=(self.object.pk,))

class BeneficiarioInternoCreateView(LoginRequiredMixin,RolPermisosMixin, CreateView):
    rol_permission_required = ('BE')
    model = models.Beneficiario
    form_class = BeneficiarioForm
    template_name = 'ayuda_integral/beneficiario/createinterno_form.html'
    
    def form_valid(self, form):
        nombres = form.cleaned_data['nombres']
        apellidos = form.cleaned_data['apellidos']
        identificador = form.cleaned_data['identificador']
        entidad = form.cleaned_data['entidad']
        alumno_registrointerno(self.request, identificador,nombres,apellidos,entidad,self.request.user)
        
        return redirect('ayuda_integral:solicitud-list')
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['entidades'] = models.Entidad.objects.filter(Q(area=models.Entidad.I)|Q(area=models.Entidad.S)|Q(area=models.Entidad.B))        
        return context
    
    def get_success_url(self):
        return reverse('ayuda_integral:solicitud-list')

def  alumno_registrointerno(request, ID, NOMBRES, APELLIDOS, ENTIDAD,user):    
    if(user.beneficiario):
        messages.error(
            request,
            'Beneficiario ya se encuentra registrado',
            extra_tags='mensaje_solicitanteinterno',
        )
    else:

        if(not (Beneficiario.objects.filter(identificador=ID).exists())):
            print(ENTIDAD)
            alumno = models.Beneficiario(
                is_interno = True,
                tipo_entidad = 'ES',
                tipo_rol = 'AL',
                nombres = NOMBRES,
                apellidos = APELLIDOS,
                identificador = ID,
                entidad = Entidad.objects.get(nombre = ENTIDAD)
            )
            alumno.save()
            user.beneficiario = alumno
            user.save()
            messages.success(
                request,
                'Beneficiario registrado exitosamente',
                extra_tags='mensaje_solicitanteinterno',
            )
        else:
            bene = Beneficiario.objects.get(identificador=ID)
            user.beneficiario = bene
            user.save()
            messages.success(
                request,
                'Beneficiario registrado exitosamente',
                extra_tags='mensaje_solicitanteinterno',
            )
    return 


class BeneficiarioExternoUpdateView(LoginRequiredMixin,RolPermisosMixin, UpdateView):
    rol_permission_required = ('AS','SG')
    model = models.Beneficiario
    form_class = BeneficiarioForm
    template_name = 'ayuda_integral/beneficiario/update_form.html'
    
    def get_success_url(self):
        return reverse('ayuda_integral:beneficiario-externo-detail', args=(self.object.pk,))

class BeneficiarioExternoDeleteview(LoginRequiredMixin,RolPermisosMixin, DeleteView):
    rol_permission_required = ('AS','SG')
    model = models.Beneficiario
    template_name = 'ayuda_integral/beneficiario/delete_form.html'
    success_url = reverse_lazy('ayuda_integral:expediente-list')

bienestar/ayuda_integral/views/derivacion.py
from main.models import UsuarioDerivacion, User, Expediente
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from main.mixins import RolPermisosMixin,rol_permission_required
from notifications.signals import notify

from django.db.models import Max

class Derivacion():
    def __init__(self,
     expediente = None, emisor = None, receptor = None):
        self.expediente = expediente
        self.emisor = emisor
        self.receptor = receptor

def derivar(derivacion: Derivacion):
    # Crear un nuevo objeto usuario derivacion con los datos de derivacion
    UsuarioDerivacion.objects.create(
        usuario= derivacion.emisor,
        usuario_derivado= derivacion.receptor,
        expediente= derivacion.expediente,
    )

    #crear una notificacion para el receptor de la derivacion
    notify.send(
        derivacion.emisor, 
        recipient=derivacion.receptor, 
        action_object=derivacion.expediente,
        verb='Te han derivado un expediente',
        description=f'{derivacion.emisor.email} te ha derivado el expediente:'
    )

def derivacion_oficina(emisor, oficina, expediente):
    '''
    Send the newly created expediente to the office's secretary
    '''
    usuario_destino = User.objects.get(
        oficina = oficina,
        rol = User.SO
    )

    
    derivar(Derivacion(
        emisor=emisor,
        receptor=usuario_destino,
        expediente=expediente
    ))

@login_required()
@rol_permission_required(('AS','SG','SO'))
def derivacion_trabajador_view(request):
    '''
    Send a list of expedientes to a list of workers
    '''
    user = request.user
    if request.method == "POST":
        # Se obtiene la lista de pks de expedientes y de usuarios
        expedientes = request.POST.get('expedientes', [])
        receptores = request.POST.get('usuarios', [])

        if isinstance(expedientes, str):
            expedientes = [expedientes]
            
        if isinstance(receptores, str):
            receptores = [receptores]
        

        for expediente_pk in expedientes:
            for receptor_pk in receptores:
                expediente = Expediente.objects.get(pk= expediente_pk)
                receptor = User.objects.get(pk= receptor_pk)
                
                derivar(Derivacion(
                    emisor=user,
                    expediente=expediente,
                    receptor=receptor
                ))
                
                messages.success(
                    request,
                    f'Se derivó el expediente {expediente} al usuario {receptor} satisfactoriamente',
                )
                #asignar un numero de informe a cada expediente que se esta derivando
                max_inf = Expediente.objects.all().aggregate(Max('n_informe'))['n_informe__max']
                expediente.n_informe = max_inf + 1 if max_inf is not None else 1
                expediente.salida_informe = f'{expediente.n_informe:04d}-2021/OAIU-SDBU'
                
                expediente.save()
        
    return redirect(
        #reverse('ayuda_integral:expediente-list')
        #redireccionar a la misma pagina de donde derivamos
        request.META.get('HTTP_REFERER')
    )

bienestar/ayuda_integral/views/documentos.py
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from main import models
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import render
from main.mixins import RolPermisosMixin,rol_permission_required

from ayuda_integral.forms import DocumentoExpedienteBeneficiarioForm

@login_required()
@rol_permission_required(('BE'))
def documento_list_view(request,pk):
    if request.user.rol == 'BE':
        documentos = models.Documento.objects.filter(usuario = request.user.id)
    else: 
        documentos = models.Documento.objects.filter(usuario = pk)
    beneficiario = models.User.objects.get(pk =request.user.id)
    return render(request,template_name='documento/documento_list.html',context={'docs': documentos,'beneficiario': beneficiario, 'pk':pk})

class ExpedienteDocsBeneficiarioCreateView(LoginRequiredMixin,RolPermisosMixin, CreateView):
    rol_permission_required = ('BE')
    model = models.Documento
    form_class = DocumentoExpedienteBeneficiarioForm

    template_name = 'documento/beneficiario_prueba_subida.html'
    success_url = reverse_lazy('ayuda_integral:documento-list')
    def form_valid(self, form):
        doc = models.Documento(
            usuario = models.User.objects.get(pk = self.request.user.id),
            nombre = form.cleaned_data['nombre'],
            path = form.cleaned_data['path'],
        )
        doc.save()
        
        return redirect('ayuda_integral:documento-list', self.kwargs.get('pk'))

    # def dispatch(self, request, *args, **kwargs):
    #     return redirect('ayuda_integral:solicitud-list')

bienestar/ayuda_integral/views/drive.py
from apiclient.discovery import build
from oauth2client.service_account import ServiceAccountCredentials
import os
from django.conf import settings

def obtenerFolderPorEmail(email):
    SCOPES = ['https://www.googleapis.com/auth/drive.readonly']
    KEY_FILE_LOCATION = os.path.join(settings.BASE_DIR,'bienestar/TramiteDocumentarioBienestar-c483db846e97.json')
    creds = ServiceAccountCredentials.from_json_keyfile_name(KEY_FILE_LOCATION, SCOPES)
    DRIVE = build('drive', 'v3', credentials=creds)

    response = DRIVE.files().list(q="mimeType = 'application/vnd.google-apps.folder' and '1BsY8Uytb_CqIgeRl-VraIGd8aYGeEq-m' in parents and name contains '" + email + "'",
                                            spaces='drive',
                                            fields='files(id, name, webViewLink, createdTime)',
                                            ).execute()

    if response.get('files', []):
        return response.get('files', [])[0]
    else:
        return None


def obtenerArchivos(folder):
    SCOPES = ['https://www.googleapis.com/auth/drive.readonly']
    KEY_FILE_LOCATION = os.path.join(settings.BASE_DIR,'bienestar/TramiteDocumentarioBienestar-c483db846e97.json')
    creds = ServiceAccountCredentials.from_json_keyfile_name(KEY_FILE_LOCATION, SCOPES)
    DRIVE = build('drive', 'v3', credentials=creds)
    files = []

    page_token = None
    while True:
        response = DRIVE.files().list(q="mimeType != 'application/vnd.google-apps.folder' and '" + folder + "' in parents",
                                            spaces='drive',
                                            fields='nextPageToken, files(id, name, webViewLink, createdTime)',
                                            pageToken=page_token).execute()
        for file in response.get('files', []):
            files.append(file)

        page_token = response.get('nextPageToken', None)
        if page_token is None:
            break
    
    return files

def eliminarNumerosInicialesDeNombre(nombre):
    if(len(nombre) > 18 and nombre[0:10].isdigit() ):
        nombre = nombre[11:]
        contador = 1
        while nombre[0].isdigit():
            nombre = nombre[1:]
            if contador == 7:
                break
            contador += 1
    return nombre

bienestar/ayuda_integral/templates/ayuda_integral/entidad/create_form.html
{% extends 'layouts/base.html' %}
{% block content %}

<div class="container-fluid mt-4">

    <div class="row">
        <div class="col-xl-8 order-xl-1 order-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Crear Entidad</h3>
                        </div>
                    </div>
                </div>
                <div class="card-body">

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="inputEmail4" class="form-control-label">{{form.nombre.label}}</label>
                                <input type="text" class="form-control form-control-alternative {%if form.nombre.errors %}is-invalid{%endif%}" 
                                    id="{{form.nombre.id_for_label}}"
                                    placeholder="{{form.nombre.label}}" name="{{form.nombre.html_name}}" value="{{form.nombre.value|default:''}}">
                                <div class="invalid-feedback">
                                    {{form.nombre.errors}}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="inputEmail4" class="form-control-label">{{form.descripcion.label}}</label>
                                <textarea class="form-control form-control-alternative {%if form.descripcion.errors %}is-invalid{%endif%}" id="{{form.descripcion.id_for_label}}"
                                placeholder="{{form.descripcion.label}}" name="{{form.descripcion.html_name}}" cols="30" rows="10">{{form.descripcion.value|default:''}}</textarea>
                                <div class="invalid-feedback">
                                    {{form.descripcion.errors}}
                                </div>
                            </div>
                        </div>
                        
                        
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="inputCity">{{form.area.label}}</label>
                                <select id="{{form.area.id_for_label}}" name="{{form.area.html_name}}"
                                    class="form-control form-control-alternative  {%if form.area.errors %}is-invalid{%endif%}">
                                    {% for item in form.area%}
                                    {{item}}
                                    {% endfor %}
                                </select>
                                <div class="invalid-feedback">
                                    {{form.area.errors}}
                                </div>
                            </div>
                        </div>
                        <button type="reset" class="btn btn-danger float-left"  onclick="javascript:window.history.back();">
                            <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-x" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                              </svg>
                            Cancelar
                        </button>
                        <button type="submit" class="btn btn-success float-right">
                            <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-check" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
                              </svg>
                            Guardar
                        </button>
                    </form>

                </div>
            </div>
        </div>

    </div>

    {% include "includes/footer.html" %}

</div>


{% endblock %}

bienestar/ayuda_integral/templates/ayuda_integral/entidad/detail.html
{% extends 'layouts/base.html' %}
{% block content %}

<div class="container-fluid mt-4">

    <div class="row">
        <div class="col-xl-8 order-xl-1 order-1">
            <div class="card bg-secondary shadow">
                <div class="card-header bg-white border-0">
                    <div class="row align-items-center">
                        <div class="col-9">
                            <h3 class="mb-0">Entidad</h3>
                        </div>
                        <div class="col-3">
                            {% if request.user.rol == 'AS' or request.user.rol == 'SG' or request.user.rol == 'SB'%} 
                            <a href="{% url 'ayuda_integral:entidad-update' object.pk %}">
                                <button class="btn btn-info float-right">
                                    <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                      </svg>
                                    Editar
                                </button>
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-row">
                        <div class="form-group col-md-8">
                            <label>Nombre</label>
                            <input type="text" class="form-control form-control-alternative" readonly 
                            value="{{object.nombre}}">
                        </div>
                        <div class="form-group col-md-4">
                            <label>Area</label>
                            <input type="text" class="form-control form-control-alternative" readonly 
                            value="{{object.get_area_display}}">
                            
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Descripción</label>
                            <input type="text" class="form-control form-control-alternative" readonly 
                            value="{{object.descripcion}}">
                    </div>

                </div>
            </div>
        </div>
    </div>

    {% include "includes/footer.html" %}

</div>

{% endblock %}

bienestar/ayuda_integral/templates/ayuda_integral/entidad/list.html
{% extends 'layouts/base.html' %}
{% block content %}
<div class="container-fluid mt-3">
    <!-- Table -->
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <h3 class="mb-0">Entidades</h3>
                </div>
                <div class="table-responsive" style="min-height: 250px;">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">N</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Descripción</th>
                                <th scope="col">Area</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entidad in object_list %}
                            <tr>
                                <td>
                                    {{forloop.counter}} 
                                </td>
                                <th>
                                    <a href="{% url 'ayuda_integral:entidad-detail' entidad.pk %}"  >
                                        {{entidad.nombre}}
                                    </a>
                                    
                                </th>
                                <td>
                                    {{entidad.descripcion}}
                                </td>
                                <td>
                                    {{entidad.get_area_display}}
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td>
                                    No hay entidades
                                </td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
                <div class="card-footer py-4">
                    <!--Pagination-->
                    <ul class="pagination justify-content-end mb-0">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" tabindex="-1">
                                <i class="fas fa-angle-left"></i>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                        </li>
                        {% endif %}

                        <li class="page-item active">
                            <label class="page-link" >{{ page_obj.number }} <span class="sr-only">(current)</span></label>
                        </li>

                        {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                                <i class="fas fa-angle-right"></i>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    {% include "includes/footer.html" %}
</div>





{% endblock %}