bienestar/ayuda_integral/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from ayuda_integral.url_patterns import expedientes, notificaciones
from django.contrib.auth.decorators import login_required, permission_required
from ayuda_integral.url_patterns import beneficiarios, solicitudes, derivacion, apoyoPsico, entidad


app_name = 'ayuda_integral'

urlpatterns = [
    path('',TemplateView.as_view(template_name='ayuda_integral/home.html'), name='home'),
    path('expedientes/', include(expedientes.urlpatterns)),
    path('expedientes/', include(derivacion.urlpatterns)),
    path('beneficiario/',include(beneficiarios.urlpatterns)),
    path('solicitud/',include(solicitudes.urlpatterns)),
    path('apoyoPsico/',include(apoyoPsico.urlpatterns)), 
    path('notificaciones/', include(notificaciones.urlpatterns)),
    path('entidad/', include(entidad.urlpatterns))
]

bienestar/bienestar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ayuda-integral/', include('ayuda_integral.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

handler404 = 'main.views.error.error_404_view'
handler500 = 'main.views.error.error_500_view'
handler403 = 'main.views.error.error_403_view'

bienestar/main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import pages,autentication
from ayuda_integral.views import expedientes
from main.views import profile

app_name='bienestar'

urlpatterns = [
    path('', pages.HomeView.as_view(), name='home'),
    path('redirecting/', pages.dispatch_view, name='dispatch'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', autentication.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', profile.profile_detail_view, name='profile'),
    path('expediente/reporte/', expedientes.ExpedienteReportView.as_view(), name='expediente-report'),
    path('expediente/reporte/<str:pk>/',expedientes.ExpedienteReporteVistaView.as_view(), name='vista-report'),
    path('expediente/reporte/actividad/<str:pk>/',expedientes.ExpedienteReporteActividadVistaView.as_view(), name='vista-report-actividad')
]

bienestar/ayuda_integral/views/apoyoPsico.py
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.generic import *
from main import api
from django import forms
from django.shortcuts import render
from main.mixins import RolPermisosMixin,rol_permission_required

@login_required()
@rol_permission_required(('AS','SG','SO','SB','JO','TS'))
def apoyoListView(request):
    solicitudes = api.apoyoPsicopedagogico()
    return render(request,template_name='ayuda_integral/apoyoPsico/list.html',context={'solicitudes':solicitudes})
    
@login_required()
@rol_permission_required(('AS','SG','SO','SB','JO','TS'))
def buscarSolicitudApoyoView(request):
    campo = request.POST.get('campo','')
    tipo = request.POST.get('tipo', '')
    solicitudes = {}
    if len(campo) != 0 and tipo == "DNI":
        solicitudes = api.obtenerSolicitudApoyoDNI(campo)
    elif len(campo) != 0 and tipo == 'CUI':
        solicitudes = api.obtenerSolicitudApoyoCUI(campo)
    else:
        print("no ingreso nada") 
    return render(request,template_name='ayuda_integral/apoyoPsico/list.html',context={'solicitudes':solicitudes})

bienestar/ayuda_integral/views/derivacion.py
from main.models import UsuarioDerivacion, User, Expediente
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from main.mixins import RolPermisosMixin,rol_permission_required
from notifications.signals import notify

from django.db.models import Max

class Derivacion():
    def __init__(self,
     expediente = None, emisor = None, receptor = None):
        self.expediente = expediente
        self.emisor = emisor
        self.receptor = receptor

def derivar(derivacion: Derivacion):
    # Crear un nuevo objeto usuario derivacion con los datos de derivacion
    UsuarioDerivacion.objects.create(
        usuario= derivacion.emisor,
        usuario_derivado= derivacion.receptor,
        expediente= derivacion.expediente,
    )

    #crear una notificacion para el receptor de la derivacion
    notify.send(
        derivacion.emisor, 
        recipient=derivacion.receptor, 
        action_object=derivacion.expediente,
        verb='Te han derivado un expediente',
        description=f'{derivacion.emisor.email} te ha derivado el expediente:'
    )

def derivacion_oficina(emisor, oficina, expediente):
    '''
    Send the newly created expediente to the office's secretary
    '''
    usuario_destino = User.objects.get(
        oficina = oficina,
        rol = User.SO
    )

    
    derivar(Derivacion(
        emisor=emisor,
        receptor=usuario_destino,
        expediente=expediente
    ))

@login_required()
@rol_permission_required(('AS','SG','SO'))
def derivacion_trabajador_view(request):
    '''
    Send a list of expedientes to a list of workers
    '''
    user = request.user
    if request.method == "POST":
        # Se obtiene la lista de pks de expedientes y de usuarios
        expedientes = request.POST.get('expedientes', [])
        receptores = request.POST.get('usuarios', [])

        if isinstance(expedientes, str):
            expedientes = [expedientes]
            
        if isinstance(receptores, str):
            receptores = [receptores]
        

        for expediente_pk in expedientes:
            for receptor_pk in receptores:
                expediente = Expediente.objects.get(pk= expediente_pk)
                receptor = User.objects.get(pk= receptor_pk)
                
                derivar(Derivacion(
                    emisor=user,
                    expediente=expediente,
                    receptor=receptor
                ))
                
                messages.success(
                    request,
                    f'Se derivó el expediente {expediente} al usuario {receptor} satisfactoriamente',
                )
                #asignar un numero de informe a cada expediente que se esta derivando
                max_inf = Expediente.objects.all().aggregate(Max('n_informe'))['n_informe__max']
                expediente.n_informe = max_inf + 1 if max_inf is not None else 1
                expediente.salida_informe = f'{expediente.n_informe:04d}-2021/OAIU-SDBU'
                
                expediente.save()
        
    return redirect(
        #reverse('ayuda_integral:expediente-list')
        #redireccionar a la misma pagina de donde derivamos
        request.META.get('HTTP_REFERER')
    )

bienestar/ayuda_integral/views/expedientes.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.edit import DeleteView 
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.generic import *
from main import models
from main.models import Entidad,Expediente, User, Beneficiario, SubActividad, HistorialDeExpediente, Actividad
from django import forms
from django.contrib.auth.mixins import PermissionRequiredMixin
from main.mixins import RolPermisosMixin,rol_permission_required
from main import api
from .derivacion import Derivacion, derivar
from django.shortcuts import render
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import PatternFill, Border, Side, Alignment, Protection, Font, GradientFill, NamedStyle
from django.http.response import HttpResponse
import json
import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Max

from .derivacion import derivacion_oficina

from ayuda_integral.forms import ExpedienteForm, ExpedienteUpdateForm, DocumentoExpedienteForm
from django.utils.timezone import datetime

from notifications.signals import notify

class ExpedienteListView(LoginRequiredMixin,RolPermisosMixin, ListView):
    rol_permission_required = ('AS','SB','JO','TS','SO','SG')
    model = models.Expediente
    paginate_by = 10
    expedientes = models.Expediente
    template_name = 'ayuda_integral/expediente/list.html'
    def get_queryset(self):
        buscar = self.request.GET.get('buscar', '')
        tipo = self.request.GET.get('tipo', '')
        mostrarConcluidos = self.request.GET.get('mostrar_concluidos', 'no')
        desde = self.request.GET.get('desde','')
        hasta = self.request.GET.get('hasta','')
        #expedientes mostrados a Jefe de oficina (JO)
        expedientes = Expediente.objects.filter(derivados__usuario_derivado = self.request.user)
        #AS y SG podran ver todos los expedientes
        if(self.request.user.rol == 'AS' or self.request.user.rol == 'SG' or self.request.user.rol == 'SB'):
            expedientes = Expediente.objects.all()
        #SO y JO podran ver los expedientes derivados a su oficina
        elif(self.request.user.rol == 'SO' or self.request.user.rol == 'JO' ):
            expedientes = Expediente.objects.filter(derivados__usuario_derivado__oficina = self.request.user.oficina, derivados__usuario_derivado__rol = 'SO')

        if(mostrarConcluidos != 'no'):
            expedientes = expedientes.filter(estado_expediente = Expediente.CO)
        if desde =="" and hasta=="":
            desde = '2021-01-01'
            hasta = datetime.today()
        if desde == "":
                desde = '2021-01-01'
        elif hasta == "":
                hasta = datetime.today()
        if buscar == "":
            expedientes = expedientes.filter(fecha_recepcion__range=(desde, hasta))
        if tipo == "beneficiario":
            expedientes = expedientes.filter(fecha_recepcion__range=(desde, hasta)).filter(beneficiario__nombres__icontains = buscar) | expedientes.filter(beneficiario__apellidos__icontains = buscar)
        elif tipo == "entidad":
            expedientes = expedientes.filter(fecha_recepcion__range=(desde, hasta)).filter(beneficiario__entidad__nombre__icontains = buscar)
        elif tipo == "area":
            expedientes = expedientes.filter(fecha_recepcion__range=(desde, hasta)).filter(beneficiario__entidad__area__icontains = buscar)
        elif tipo == "actividad":
            expedientes = expedientes.filter(fecha_recepcion__range=(desde, hasta)).filter(actividad__nombre__icontains = buscar)
        elif tipo == "subactividad":
            expedientes = expedientes.filter(fecha_recepcion__range=(desde, hasta)).filter(sub_actividad__nombre__icontains = buscar)
        elif tipo == "expediente":
            expedientes = expedientes.filter(fecha_recepcion__range=(desde, hasta)).filter(numero_expediente__icontains = buscar)
        elif tipo == "proveido":
            expedientes = expedientes.filter(fecha_recepcion__range=(desde, hasta)).filter(numero_proveido__icontains = buscar)
        elif tipo == "oficio":
            expedientes = expedientes.filter(fecha_recepcion__range=(desde, hasta)).filter(numero_oficio__icontains = buscar)
        expedientes = expedientes.order_by('numero_expediente')
        return expedientes.order_by('-fecha_recepcion')

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['contador'] = self.get_queryset().count()
        context['expedientes'] = models.Expediente.objects.exclude(estado_expediente=models.Expediente.CO).exclude(derivados__usuario=self.request.user).filter(derivados__usuario_derivado = self.request.user)
        context['usuarios'] = models.User.objects.exclude(
            pk= self.request.user.pk
        ).filter(
            rol = 'TS'
        )
        context['mostrarConcluidos'] = self.request.GET.get('mostrar_concluidos', 'no')
        context['buscar'] = self.request.GET.get('buscar', '')
        context['desde'] = self.request.GET.get('desde', '')
        context['hasta'] = self.request.GET.get('hasta', '')
        context['tipo'] = self.request.GET.get('tipo', '')

        return context

def compararExpediente(pk, expediente):
    expedientes = models.UsuarioDerivacion.objects.filter(usuario_derivado = pk, expediente = expediente)
    if expedientes:
        return True
    else:
        return False

class ExpedienteDetailView(LoginRequiredMixin,RolPermisosMixin, DetailView):
    rol_permission_required = ('AS','JO','TS','SG','SB', 'SO')
    model = models.Expediente
    template_name = 'ayuda_integral/expediente/detail.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.rol =="TS":
            if not compararExpediente(self.request.user,self.get_object()):
                return self.handle_no_permission()

        return super().dispatch(request, *args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        expediente = self.get_object()
        if not expediente.usuario_beneficiario:
            context['docPersonal'] = None
        else:
            context['docPersonal'] = expediente.usuario_beneficiario.documento_set.all()
        context['usuarios'] = models.User.objects.exclude(
            pk= self.request.user.pk
        ).filter(
            rol = 'TS'
        )
        context['se_puede_derivar'] = models.UsuarioDerivacion.objects.filter(usuario=self.request.user, expediente=self.get_object()).count() == 0
        return context

class ExpedienteDocsCreateView(LoginRequiredMixin,RolPermisosMixin, CreateView):
    rol_permission_required = ('AS','JO','TS','SG','SB','SO')
    model = models.DocumentoExpediente
    form_class = DocumentoExpedienteForm

    template_name = 'ayuda_integral/expediente/document_create.html'
    success_url = reverse_lazy('ayuda_integral:expediente-list')
    def form_valid(self, form):
        documento = models.DocumentoExpediente(
            nombre = form.cleaned_data['nombre'],
            path = form.cleaned_data['path'],
            expediente =models.Expediente.objects.get(pk = self.kwargs.get('pk'))
        )
        documento.save()
        return redirect('ayuda_integral:expediente-detail', self.kwargs.get('pk'))

class ExpedienteDocsDeleteView(DeleteView): 
    model = models.DocumentoExpediente 

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

class ExpedienteCreateView(LoginRequiredMixin,RolPermisosMixin, CreateView):
    rol_permission_required = ('AS','SG')
    form_class = ExpedienteForm
    
    template_name = 'ayuda_integral/expediente/create_form.html'
    success_url = reverse_lazy('ayuda_integral:expediente-list')

    def form_valid(self, form):
        beneficiario = None
        solicitud = None
        usuarioBeneficiario = None
        creado_a_partir_de_solicitud = False
        if( self.kwargs.get('pk')):
            # Caso que entra por parte de una solicitud
            # obtencion del id de la solicitud que creo el expediente
            solicitud = models.Solicitud.objects.get(pk=self.kwargs.get("pk"))
            beneficiario = solicitud.usuario.beneficiario
            creado_a_partir_de_solicitud = True
        else:
            beneficiario = form.cleaned_data['beneficiario']


        try:
            usuarioBeneficiario = beneficiario.user
        except ObjectDoesNotExist:
            usuarioBeneficiario = None

        expediente = models.Expediente(
            fecha_recepcion=form.cleaned_data['fecha_recepcion'],
            numero_expediente=form.cleaned_data['numero_expediente'],
            descripcion=form.cleaned_data['descripcion'],
            numero_proveido=form.cleaned_data['numero_proveido'],
            numero_oficio=form.cleaned_data['numero_oficio'],
            beneficiario=beneficiario,
            usuario_beneficiario=usuarioBeneficiario, #el usuario vinculado con beneficiario
            actividad=form.cleaned_data['actividad'],
            sub_actividad=form.cleaned_data['sub_actividad'],
        )
        if(creado_a_partir_de_solicitud):
            #asignar n_expediente_solicitud
            max_exp_sol = models.Expediente.objects.all().aggregate(Max('n_expediente_solicitud'))['n_expediente_solicitud__max']
            expediente.n_expediente_solicitud = max_exp_sol + 1 if max_exp_sol is not None else 1
            #asignar numero de expediente
            expediente.numero_expediente = f'{expediente.n_expediente_solicitud:04d}-2021/SDBUint'
            #copiar salida_expediente
            expediente.salida_expediente = expediente.numero_expediente
        else:

bienestar/ayuda_integral/views/notificaciones.py
from django.shortcuts import redirect
from django.views.generic import DetailView
from main.models import User, Expediente



class NotificacionView(DetailView):
    def get(self, request, pk):
        notification = request.user.notifications.get(pk=pk)
        notification.unread = False
        notification.save()
        action_object = notification.action_object
        if isinstance(action_object, Expediente):
            return redirect("ayuda_integral:expediente-detail", pk=action_object.pk)
        
        return redirect("ayuda_integral:expediente-list")

bienestar/ayuda_integral/templates/ayuda_integral/expediente_list.html
<!--
<h5>
    Derivar Expedientes
</h5>
<label >Expedientes:</label>
    <select form="derivacion-form" id="expediente" name="expedientes" >
    {% for expediente in expedientes %}
    <option value="{{ expediente.pk }}">{{expediente.numero_expediente}}  </option>
    {% endfor %}
</select>
<label >Usuarios:</label>
<select form="derivacion-form" id="usuario" name="usuarios"  placeholder="Escoja un usuario">
{% for user in usuarios %}
    <option value="{{ user.pk }}"> {{ user.email }} </option>
{% endfor %}
</select>
<button form="derivacion-form" type="submit" >Derivar</button>
<div class="d-none">
    <div id="usuario-actual" data-id="{{ request.user.pk }}"></div>
    <form id="derivacion-form" action="{% url 'expediente-derivar' %}" method="POST">
        {% csrf_token %}
    </form>
</div>
-->

bienestar/ayuda_integral/templates/ayuda_integral/expediente_report.html
<h1>REPORTE DE EXPEDIENTES</h1>
<form method="GET">
    <input type="text" class="form-control" placeholder="Buscar por..." name="buscar">
    <select name="tipo" id="tipo">
    <option value="beneficiario">beneficiario</option>
    <option value="entidad">entidad</option>
    <option value="area">area</option>
    <option value="actividad">actividad</option>
    </select>
    <button type="submit" class="boton bton-success">Buscar</button>
    {% csrf_token %}
</form>

{% if object_list %}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Nº</th>
            <th scope="col">entidad</th>
            <th scope="col">area</th>
            <th scope="col">Beneficiario</th>
            <th scope="col">Actividad</th>
        </tr>
    </thead>
    <tbody>
        {% for article in object_list %}
        <tr>
            <th>
                {{article.numero_expediente}}
            </th>
            <th>
                {{article.beneficiario.entidad}}
            </th>
            <th>
                {{article.beneficiario.entidad.area}}
            </th>
            <th>
                {{article.beneficiario}}
            </th>
            <th>
                {{article.actividad}}
            </th>
        </tr>
        {% empty %} {% endfor %}
    </tbody>

</table>
{% else %}
<ul>
    <li>No se encontraron expedientes.</li>
</ul>
{% endif %}
<h2>Numero de expedientes: {{contador}}</h2>

bienestar/ayuda_integral/templates/ayuda_integral/expedientes_report.html
{% extends 'layouts/base.html' %}
{% block content %}
<div class="container-fluid mt-3">

    <div class="row mx-2">
        <div class="col">
        <form method="GET">
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label>Desde</label>
                    <input type="date"
                        class="form-control form-control-alternative"
                        value="{{desde}}"
                        name="desde">
                </div>
                <div class="form-group col-md-4">
                    <label>Hasta</label>
                    <input type="date"
                        class="form-control form-control-alternative"
                        name="hasta"
                        value="{{hasta}}">
                </div>
            </div>
            <div class="form-row">
                
                <div class="form-group col-sm-6 col-md-3">
                    <select name="tipo" id="tipo" class="form-control form-control-alternative">
                        <option value="escuela" {% if categoria == 'escuela' %}selected{% endif %}>Escuela</option>
                        <option value="area" {% if categoria == 'area' %}selected{% endif %}>Area</option>
                        <option value="beneficiarios" {% if categoria == 'beneficiarios' %}selected{% endif %}>Beneficiarios</option>
                        <option value="actividad" {% if categoria == 'actividad' %}selected{% endif %}>Actividad</option>

                    </select>
                </div>

                <div class="form-group col-sm-6">
                    <button type="submit" class="btn btn-success">
                        <svg width="20px" height="20px" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                            <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                          </svg>
                        Buscar
                    </button>
                </div>
            </div>
        </form>
    </div>



    </div>

    <!-- Table -->
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <h3 class="mb-0">Reporte de expedientes</h3>
                </div>
                <div class="table-responsive" style="min-height: 250px;">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Cantidad</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if tipo.items %}
                            {%for key, value in tipo.items%}
                            <tr>
                                <td>
                                    {{key}}
                                </td>
                                <th>
                                    {% if value > 0 %}
                                        {{value}}
                                    {% else %}
                                        {% widthratio   value 1 -1 %}
                                    {% endif %}
                                </th>
                                {{vacios}}
                                <td>
                                    {% if value > 0 %}
                                        {% if tipo_ %}
                                            {% if subactividad == 'vacio' %}
                                                <a href="{%url 'bienestar:vista-report' key %}">Ver</a>
                                            {% else %}
                                                <a href="{%url 'bienestar:vista-report-actividad' key %}">Ver</a>
                                            {% endif %}  
                                        {% else %}
                                            <a href="{%url 'bienestar:vista-report' key %}">Ver</a>
                                        {% endif %}
                                    {% elif value < 0%}
                                        <a href="{%url 'bienestar:vista-report' key %}">Ver</a>
                                    {% else %}
                                        ver
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td>
                                    
                                </td>
                            </tr>

                            {% endif %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer py-4">

                </div>
            </div>
        </div>
    </div>

    {% include "includes/footer.html" %}
</div>

{% endblock %}

bienestar/ayuda_integral/templates/ayuda_integral/expedientes_report_actividad.html
{% extends 'layouts/base.html' %}
{% block content %}
<div class="container-fluid mt-3">
    <!-- Table -->
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <h3 class="mb-0">Reporte por sub actividad</h3>
                </div>
                <div class="table-responsive" style="min-height: 250px;">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Sub Actividad</th>
                                <th scope="col">Cantidad</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if tipo.items %}
                            {%for key, value in tipo.items%}
                            <tr>
                                <td>
                                    {{key}}
                                </td>
                                <th>
                                    {{value}}
                                </th>
                                <td>
                                    {% if value > 0 %}
                                        {% if tipo_ %}
                                            <a href="{%url 'bienestar:vista-report-actividad' key %}">Ver</a>
                                        {% else %}
                                            <a href="{%url 'bienestar:vista-report' key %}">Ver</a>
                                        {% endif %}
                                    {% else %}
                                        ver
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td>
                                    No se encontró lo que se buscaba
                                </td>
                            </tr>

                            {% endif %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer py-4">

                </div>
            </div>
        </div>
    </div>

    {% include "includes/footer.html" %}
</div>

{% endblock %}

bienestar/ayuda_integral/templates/ayuda_integral/home.html
{% extends 'layouts/base.html' %}
{% block content %}
<div class="container-fluid  mt-3 pb-5">
    <div class="row">
        <h1>
           
        </h1>
    </div>
</div>
{% endblock %}